name: jeka
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  auto_route: ^8.1.3
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.17.5
  dartz: ^0.10.1
  dio: ^5.4.3+1
  dots_indicator: ^3.0.0
  equatable: ^2.0.5
  expansion_tile_group: ^1.2.4
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_easyloading: ^3.0.5
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  injectable: ^2.4.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  loading_animation_widget: ^1.2.1
  shared_preferences: ^2.2.3
  skeletonizer: ^1.3.0

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.10
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  icons_launcher: ^2.1.7
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/onboarding/
