// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaUU9fGzVBn6pOytngxd4X7LKnEGNEYc8',
    appId: '1:867130052345:android:459428dca1e34b4650dc28',
    messagingSenderId: '867130052345',
    projectId: 'jeka-85742',
    storageBucket: 'jeka-85742.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFd421grza9RGDHfO2BtYZHnBOXosOLno',
    appId: '1:867130052345:ios:4dbfeed3a38b29fc50dc28',
    messagingSenderId: '867130052345',
    projectId: 'jeka-85742',
    storageBucket: 'jeka-85742.appspot.com',
    androidClientId: '867130052345-1lfcg4pe75vui4ml9bpmekoo3vj2tlfq.apps.googleusercontent.com',
    iosClientId: '867130052345-vl00lr3prc5jq7109vcvf4abjca4c2s7.apps.googleusercontent.com',
    iosBundleId: 'com.example.jeka',
  );

}